echo Generate XSLT Concept Mapping Script ...
"%JAVA_HOME%\java" -jar %XALAN% -IN ..\input\%3.xml -XSL ..\generator_v1/create_concept_mapping_script.xslt -OUT ..\generator_v1\concept_mapping_script.xslt
echo Generate Java Class %1.java ...
"%JAVA_HOME%\java" -jar %XALAN% -IN ..\input\%2.xml -XSL ..\generator_v1/create_bd_evaluation_for_java_v1.xslt -OUT %1\%1.java
echo .