echo Generate XML tempfile for BD Test cases ...
"%JAVA_HOME%\java" -jar %XALAN% -IN ..\input\%2.xml -XSL ..\generator_v1/create_bd_testcase_tempfile.xslt -OUT %1\tempfile_testcase.xml
echo Generate XML File with Test cases ...
"%JAVA_HOME%\java" -jar %XALAN% -IN %1\tempfile_testcase.xml -XSL ..\generator_v1/create_bd_testcase.xslt -OUT %1\%1_test_cases_template.xml
del %1\tempfile_testcase.xml
echo Generate Html File with Test cases view ...
"%JAVA_HOME%\java" -jar %XALAN% -IN %1\%1_test_cases.xml -XSL ..\visualisierung_v5/business_decision_testcase_view.xslt -OUT %1\%1_test_cases.html
echo Generate Java Methods for Testcases ...
"%JAVA_HOME%\java" -jar %XALAN% -IN %1\%1_test_cases.xml -XSL ..\generator_v1\create_bd_testcase_methods_for_java.xslt -OUT %1\%1_testcases_methods.java
echo .